//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadTrainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeadTrainer()
        {
            this.Trainers = new HashSet<Trainer>();
        }
    
        public int HeadTrainerID { get; set; }
        public string Subject { get; set; }
        public int PersonID { get; set; }
        public int PrivateSchoolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainer> Trainers { get; set; }
        public virtual Person Person { get; set; }
        public virtual Private_School Private_School { get; set; }

        public override string ToString()
        {
            return $"\n ID: {HeadTrainerID} Subject : {Subject} First Name: {Person.FirstName} Last Name: {Person.LastName} \n \n  Private_School: {Private_School} Trainers Managing: {Trainers.Count}";
        }
    }
}
