//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ManagerID { get; set; }
        public Nullable<decimal> AnnualPayment { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }

        public override string ToString()
        {
            return $"\n ID: {ManagerID} AnnualPayment : {AnnualPayment} First Name: {Person.FirstName} Last Name: {Person.LastName} ";
        }
    }
}
