//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatu
    {
        public Nullable<bool> PaymentStatusDescription { get; set; }
        public int PaymentID { get; set; }
        public int PaymentIDCode { get; set; }
        public Nullable<double> PaymentStatusCode { get; set; }
    
        public virtual Payment Payment { get; set; }

        public override string ToString()
        {
            return $"\n Status: {PaymentStatusDescription} PaymentStatusCode : {PaymentStatusCode} \t Payment Amount: {Payment.Amount} ";
        }
    }
}
