//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Private_School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Private_School()
        {
            this.HeadTrainers = new HashSet<HeadTrainer>();
        }
    
        public int PrivateSchoolID { get; set; }
        public string Inventory { get; set; }
        public string Name { get; set; }
        public int ManagerID { get; set; }
        public Nullable<decimal> Expenses { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeadTrainer> HeadTrainers { get; set; }

        public override string ToString()
        {
            return $"\n ID: {PrivateSchoolID} Inventory : {Inventory} First Name: {Name} Expenses: {Expenses}\n";
        }
    }
}
