//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream
    {
        public string Stream_Name { get; set; }
        public string Stream_Type { get; set; }
        public int StreamID { get; set; }
        public int CourseID { get; set; }
        public Nullable<double> StreamCode { get; set; }
    
        public virtual Course Course { get; set; }

        public override string ToString()
        {
            return $"\n StreamCode: {StreamCode} Name : {Stream_Name} Type: {Stream_Type} Course.Title: {Course.Title}  ";
        }
    }
}
