//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartBMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int TrainerID { get; set; }
        public string Subject { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> HeadTrainerID { get; set; }
        public Nullable<int> PrivateSchoolID { get; set; }
    
        public virtual HeadTrainer HeadTrainer { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }

        public override string ToString()
        {
            return $"\n ID: {TrainerID} Subject : {Subject} First Name: {Person.FirstName} Last Name: {Person.LastName} \n \n  Headtrainer: {HeadTrainer.Person.FirstName} ";
        }
    }
}
